[package]
name = "custos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
lazy_static = "1.4.0"

[features]
default = ["all"]
all = ["cpu", "opencl"]
cpu = []
opencl = []