[package]
name = "custos"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A library for matrix operations calculated on the CPU and OpenCL devices"
repository = "https://github.com/elftausend/custos"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"

[features]
default = ["opencl"]
opencl = []
cuda = []
safe = []


[[example]]
name = "unified_memory"
required-features = ["opencl"]

[[example]]
name = "simple"
required-features = ["opencl"]

[[example]]
name = "opencl_kernel_launch"
required-features = ["opencl"]

[[example]]
name = "cl_device"
required-features = ["opencl"]


[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "safe_vs_cache"
harness = false

[[bench]]
name = "fixed_size_vs_vec"
harness = false

[[bench]]
name = "remove_value"
harness = false

[[bench]]
name = "gemm"
harness = false
required-features = ["opencl", "cuda"]

[[bench]]
name = "cuda_vs_opencl"
harness = false
required-features = ["opencl", "cuda"]
