[package]
name = "custos"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A library for matrix operations calculated on CPU and OpenCL devices"
repository = "https://github.com/elftausend/custos"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#rand = "*"
lazy_static = "1.4.0"

[features]
default = ["opencl"]
opencl = []
safe = []


[dev-dependencies]
criterion = "0.3"


[[bench]]
name = "safe_vs_cache"
harness = false