name: GPU

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-opencl:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build (OpenCL)
      run: cargo build --verbose --no-default-features --features opencl
  
  build-cuda:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build (CUDA)
      run: cargo build --verbose --no-default-features --features cuda

  build-both:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build (CUDA)
      run: cargo build --verbose --no-default-features --features cuda,opencl
      
  test-opencl:
  
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Run tests (OpenCL)
      run: cargo test --verbose --no-default-features --features opencl
    - name: Run tests (OpenCL, lazy)
      run: cargo test --verbose --no-default-features --features opencl,lazy
    - name: Run tests (OpenCL, autograd)
      run: cargo test --verbose --no-default-features --features opencl,autograd
    - name: Run tests (OpenCL, graph)
      run: cargo test --verbose --no-default-features --features opencl,graph
  
  test-cuda:
  
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Run tests (CUDA)
      run: cargo test --verbose --no-default-features --features cuda
    - name: Run tests (CUDA, lazy)
      run: cargo test --verbose --no-default-features --features cuda,lazy
    - name: Run tests (CUDA, autograd)
      run: cargo test --verbose --no-default-features --features cuda,autograd
    - name: Run tests (CUDA, graph)
      run: cargo test --verbose --no-default-features --features cuda,graph

  test-all:
  
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Run tests (CUDA, OpenCL)
      run: cargo test --verbose --no-default-features --features cuda,opencl
    - name: Run tests (CUDA, OpenCL, lazy)
      run: cargo test --verbose --no-default-features --features cuda,opencl,lazy
    - name: Run tests (CUDA, OpenCL, autograd)
      run: cargo test --verbose --no-default-features --features cuda,opencl,autograd